Note failures of subcommands and exit early on failures.

diff --git a/get-addon b/get-addon
--- a/get-addon
+++ b/get-addon
@@ -216,7 +216,11 @@ do
         then
             echo "$command"
         else
-            $command
+            if ! $command
+            then
+                echo "Error: Command failed"
+                exit 1;
+            fi
         fi
     fi
 done
